language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - npm run lh -- http://d2avoqs20x6i3n.cloudfront.net
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
