language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "release" ]; then npm run lh; fi
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
