language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
  - if [ "$TRAVIS_BRANCH" = "feature/lighthouse-ci" ]; then npm run lh -- --pwa=45 --perf=90 --a11y=75 --bp=86 --seo=85 http://d2avoqs20x6i3n.cloudfront.net; fi
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
