language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - [ $TRAVIS_BRANCH == "feature/lighthouse-ci" ] && npm run lh -- --pwa=45 --perf=90 --a11y=75 --bp=86 --seo=85 https://store.buildit.digital
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
