language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
deploy:
  - provider: script
    script: npm run lh
    on:
      branch: feature/lighthouse-ci
      condition: $TRAVIS_PULL_REQUEST != false
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: feature/lighthouse-ci
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
