language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: feature-aws-deploy
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
