language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
deploy:
  provider: script
  script: echo "blablabl"
  on:
    branch: master
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a