language: node_js
node_js:
  - 10
install:
  - npm ci
  - npm install -g codecov
cache: npm
script:
  - npm run test:ci
  - npm run lint
  - npm run format:check
  - codecov
  - $TRAVIS_BRANCH == "feature/lighthouse-ci" && npm run lh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
notifications:
  slack: wiprodigital:f0IX6BV1OmlTrsGdZHf9fz3a
