codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "src/e2eConfig.js"
  - "src/index.js"
  - "src/serviceWorker.js"
  - "src/components/Root/*"
  - "src/components/GlobalStyle/*"
  - "src/constants/*"

comment: off
