codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: '70...100'

  status:
    project: yes
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - 'src/e2eConfig.js'
  - 'src/index.js',
  - 'src/serviceWorker.js',
  - 'src/components/Root/*',
  - 'src/constants/*'

comment: off
