export const INCREASE_COUNT = 'INCREASE_COUNT';
export const SET_QUANTITY = 'SET_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
