// Cart
export const CART_SET_ITEM_QUANTITY = '@@CART/SET_ITEM_QUANTITY';
export const CART_INCREASE_ITEM_QUANTITY = '@@CART/INCREASE_ITEM_QUANTITY';
export const CART_DECREASE_ITEM_QUANTITY = '@@CART/DECREASE_ITEM_QUANTITY';
export const CART_REMOVE_ITEM = '@@CART/REMOVE_ITEM';

// CHECKOUT
export const CHECKOUT_SET_SHIPPING_ADDRESS = '@@CHECKOUT/SET_SHIPPING_ADDRESS';
